export const WEB3STATE_LOCKED = 'WEB3STATE_LOCKED'
export const WEB3STATE_UNLOCKED = 'WEB3STATE_UNLOCKED'
export const WEB3STATE_NOT_INSTALLED = 'WEB3STATE_NOT_INSTALLED'
export const WEB3STATE_LOADING = 'WEB3STATE_LOADING'
export const WEB3STATE_ERROR = 'WEB3STATE_ERROR'

export const WALLET_METAMASK = 'WALLET_METAMASK'
export const WALLET_LEDGER = 'WALLET_LEDGER'
