export const STEP_CONNECT_YOUR_ACCOUNT = 'STEP_CONNECT_YOUR_ACCOUNT'
export const STEP_WRAP_ETHER = 'STEP_WRAP_ETHER'
export const STEP_WETH_PERMISSION = 'STEP_WETH_PERMISSION'
export const STEP_GET_ZRX = 'STEP_GET_ZRX'
export const STEP_ZRX_PERMISSION = 'STEP_ZRX_PERMISSION'
export const STEP_CREATE_ORDER = 'STEP_CREATE_ORDER'

export const STANDALONE_CONNECT = 'STANDALONE_CONNECT'
export const STANDALONE_PERMISSION = 'STANDALONE_PERMISSION'
export const PARTIAL_FILL = 'PARTIAL_FILL'
export const TIMEPICKER = 'TIMEPICKER'

export const METAMASK_URL = 'https://metamask.io/'
export const LEDGER_URL = 'https://www.ledger.com/?r=004044e751ee'
